name: test azure deployments
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and push image
      run: |
        docker build -t olehnest.azurecr.io/my-nest-app:${{ github.sha }} .
        docker push olehnest.azurecr.io/my-nest-app:${{ github.sha }}
    
    - name: Deploy US instance
      run: |
        az webapp config container set \
          --name my-nest-us \
          --resource-group rg-us \
          --docker-custom-image-name olehnest.azurecr.io/my-nest-app:${{ github.sha }} \
          --docker-registry-server-url https://olehnest.azurecr.io
    
    - name: Deploy EU instance
      run: |
        az webapp config container set \
          --name my-nest-eu \
          --resource-group rg-eu \
          --docker-custom-image-name olehnest.azurecr.io/my-nest-app:${{ github.sha }} \
          --docker-registry-server-url https://olehnest.azurecr.io
